// ── Story Mode — chapter configuration ───────────────────────────────────────
//
// A chapter is DATA. It never contains game logic: it only describes what to
// set up. The existing engine plays it — same placeTile, same endRound, same
// rules as live multiplayer.
//
// CHALLENGE TYPES
//
//   { type: 'match', ... }   a normal game
//       seats      4 (default) or 2
//       pile       true for 1v1 with a draw pile (2 seats only)
//       opponents  bot names, seated clockwise from the player
//       partner    'pick' | a bot name | null   (4 seats only; seat 2)
//       rounds     1 (default) or 3 for a boss match
//
//   { type: 'puzzle', ... }  a fixed position with a stated goal
//       deal       { hands: [[...], ...], board: [...], turn: 0 }
//       objective  see OBJECTIVES below
//       moves      optional cap — "solve it in at most N moves"
//
// OBJECTIVES
//   'win'         empty your hand first
//   'dekabess'    go out on a tile matching BOTH ends
//   'block'       jam the round while holding the fewest pips
//   'forcePass'   make a named opponent knock (count: n)
//
// STARS
//   3 = met the objective within `moves`
//   2 = met the objective
//   1 = finished but missed the objective
//
// UNLOCKING
//   Completing a chapter unlocks its featured bot for free play, partner
//   selection and later chapters. A chapter's featured bot can never be the
//   player's partner inside its own chapter.

export const NORMAL_CIRCUIT = [
  'Ti-Bebe', 'Ti-Sak', 'Ti-Pridan', 'Ti-Cam',
  'Ti-Jean', 'Ti-Djo', 'Ti-Mèt', 'Ti-Doub',
]

export const EXPERT_CIRCUIT = [
  'Ti-Jòj', 'Ti-Tid', 'Ti-Roro', 'Ti-Chasè',
  'Ti-Frè', 'Ti-Chaj', 'Ti-Pyèj', 'Ti-Wa',
]

export const CHAPTERS = [
  {
    id: 1,
    tier: 'normal',
    intro: "Everybody starts at the small table.\n\nTi-Bebe is the one they let win sometimes, just to keep him at the table. He plays whatever looks nice in his hand and never counts what's already down.\n\nSit. Watch the two ends. That's all there is at first.",
    outro: "Ti-Bebe laughs and pulls up a chair beside you. He's yours now \u2014 bring him along when you need an easy partner.",
    featured: 'Ti-Bebe',
    title: 'Premye Kou',
    theme: 'Placing tiles, reading the two ends',
    unlocks: 'Ti-Bebe',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Bebe'],
        rounds: 1,
        brief: 'Just the two of you. Seven tiles each — draw from the pile when you cannot play.',
      },
      {
        id: 2,
        type: 'puzzle',
        brief: 'Three tiles, three moves. Steer both ends so your last tile closes on both.',
        objective: { kind: 'dekabess' },
        moves: 3,
        deal: {
          // seat 0 = you. Board reads 1-6 6-4, so the ends are 1 and 4.
          // 1-2 on the left makes it 2; 4-5 on the right makes it 5;
          // 2-5 then matches BOTH ends and empties your hand — Dekabess.
          hands: [
            [[1, 2], [4, 5], [2, 5]],
            [[0, 0], [3, 3]],
            [[0, 1], [3, 5]],
            [[6, 6], [0, 2]],
          ],
          board: [
            { tile: [1, 6], flipped: false },
            { tile: [6, 4], flipped: false },
          ],
          left_end: 1,
          right_end: 4,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Bebe', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table. Three of them, all still learning.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Bebe'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Beat him twice and he joins your table.',
      },
    ],
  },

  // Chapters 2-8 follow the same shape, in measured difficulty order.
  // Listed here so the story map can render them locked.
  {
    id: 2,
    tier: 'normal',
    intro: "Ti-Sak they call the sack, because nothing ever leaves his hand.\n\nHe holds his doubles like money in a pocket, waiting for the perfect moment that usually never comes. When the table jams, he's the one caught with the weight.\n\nMake it jam.",
    outro: "He empties the sack at last. Ti-Sak plays with you now \u2014 he's patient, and patience wins the long ones.",
    featured: 'Ti-Sak',
    title: 'Sak La',
    theme: "He keeps his doubles back. Make him pay for the weight he's carrying.",
    unlocks: 'Ti-Sak',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Sak'],
        rounds: 1,
        brief: "He keeps his doubles back. Make him pay for the weight he's carrying.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Three tiles left. One order empties your hand on both ends at once.",
        objective: { kind: 'dekabess' },
        moves: 3,
        deal: {
          hands: [[[5, 6], [2, 4], [4, 5]], [[6, 6], [0, 5]], [[1, 5], [1, 3]], [[2, 2], [0, 3]]],
          board: [
            { tile: [2, 5], flipped: false },
            { tile: [3, 5], flipped: false },
            { tile: [3, 6], flipped: false }
          ],
          left_end: 2,
          right_end: 6,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Sak', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Sak across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Sak'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Sak joins your table.',
      },
    ],
  },
  {
    id: 3,
    tier: 'normal',
    intro: "Ti-Pridan counts. Not the tiles you have \u2014 the ones you're stuck with.\n\nHe throws his heavy tiles out early, always. Ask him why and he'll tell you: when the board closes, the lightest hand walks away with it.\n\nHe's not wrong.",
    outro: "Ti-Pridan nods once. That's approval. He'll count for your side from now on.",
    featured: 'Ti-Pridan',
    title: 'Konte Pwen',
    theme: "He sheds his heavy tiles early. If the table jams, he'll be holding almost nothing.",
    unlocks: 'Ti-Pridan',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Pridan'],
        rounds: 1,
        brief: "He sheds his heavy tiles early. If the table jams, he'll be holding almost nothing.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Three tiles, three moves. Get them all down before he stops you.",
        objective: { kind: 'win' },
        moves: 3,
        deal: {
          hands: [[[2, 6], [1, 2], [4, 6]], [[1, 1], [0, 1]], [[0, 2], [3, 6]], [[1, 5], [5, 5]]],
          board: [
            { tile: [4, 5], flipped: false },
            { tile: [0, 5], flipped: false },
            { tile: [0, 3], flipped: false },
            { tile: [3, 4], flipped: false }
          ],
          left_end: 4,
          right_end: 4,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Pridan', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Pridan across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Pridan'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Pridan joins your table.',
      },
    ],
  },
  {
    id: 4,
    tier: 'normal',
    intro: "Ti-Cam plays for the ending, not the middle.\n\nEvery hand, he's looking for the one tile that shuts both ends at the same time. Dekabess. He'll throw away a safe game chasing it, and every so often he catches it.\n\nDon't let him.",
    outro: "Ti-Cam grins \u2014 he respects someone who saw it coming. He's on your side now, chasing endings for you instead.",
    featured: 'Ti-Cam',
    title: 'Chans',
    theme: "He hunts the Dekabess. Close the ends he needs.",
    unlocks: 'Ti-Cam',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Cam'],
        rounds: 1,
        brief: "He hunts the Dekabess. Close the ends he needs.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Four tiles. Steer the ends so your last one closes on both.",
        objective: { kind: 'dekabess' },
        moves: 4,
        deal: {
          hands: [[[3, 4], [4, 6], [0, 6], [2, 3]], [[4, 5], [2, 4]], [[4, 4], [5, 5]], [[6, 6], [1, 2]]],
          board: [
            { tile: [0, 5], flipped: false },
            { tile: [2, 5], flipped: false },
            { tile: [2, 2], flipped: false }
          ],
          left_end: 0,
          right_end: 2,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Cam', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Cam across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Cam'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Cam joins your table.',
      },
    ],
  },
  {
    id: 5,
    tier: 'normal',
    intro: "Ti-Jean doesn't want to win pretty. He wants you to sit there holding tiles you can't play.\n\nHe closes numbers. He watches which ends you need and takes them away one by one. Against him the board gets smaller every turn.\n\nLeave yourself a way out.",
    outro: "Ti-Jean shrugs like it was nothing. He'll close the board for you now instead of against you.",
    featured: 'Ti-Jean',
    title: 'Bloke',
    theme: "He squeezes your options. Keep a way out.",
    unlocks: 'Ti-Jean',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Jean'],
        rounds: 1,
        brief: "He squeezes your options. Keep a way out.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Four tiles and one way through. Find the order.",
        objective: { kind: 'win' },
        moves: 4,
        deal: {
          hands: [[[3, 6], [3, 3], [3, 5], [4, 5]], [[5, 5], [2, 2]], [[0, 5], [4, 4]], [[4, 6], [0, 0]]],
          board: [
            { tile: [0, 2], flipped: false },
            { tile: [1, 2], flipped: false },
            { tile: [0, 1], flipped: false },
            { tile: [0, 4], flipped: false }
          ],
          left_end: 0,
          right_end: 4,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Jean', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Jean across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Jean'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Jean joins your table.',
      },
    ],
  },
  {
    id: 6,
    tier: 'normal',
    intro: "Ti-Djo has no trick. That's what makes him hard.\n\nHe protects his own hand, takes the blocks that are cheap, and never gives you a free number. Everything the last five taught you, he does all at once.\n\nThis is the real test of the small table.",
    outro: "Ti-Djo shakes your hand. You've earned the strongest of the regulars \u2014 and you'll need him.",
    featured: 'Ti-Djo',
    title: 'Estrateji',
    theme: "No weakness to exploit \u2014 he simply plays well.",
    unlocks: 'Ti-Djo',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Djo'],
        rounds: 1,
        brief: "No weakness to exploit \u2014 he simply plays well.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Four tiles. The finish is there — the ends have to be set up first.",
        objective: { kind: 'dekabess' },
        moves: 4,
        deal: {
          hands: [[[2, 2], [2, 3], [4, 6], [2, 6]], [[5, 6], [1, 6]], [[3, 4], [3, 6]], [[3, 3], [0, 1]]],
          board: [
            { tile: [4, 5], flipped: false },
            { tile: [2, 5], flipped: false },
            { tile: [0, 2], flipped: false },
            { tile: [0, 0], flipped: false },
            { tile: [0, 3], flipped: false }
          ],
          left_end: 4,
          right_end: 3,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Djo', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Djo across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Djo'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Djo joins your table.',
      },
    ],
  },
  {
    id: 7,
    tier: 'normal',
    intro: "Ti-M\u00e8t picks a number and makes the whole table play his way.\n\nWhatever he's deep in, he keeps showing. While that number is open he always has an answer, and you're the one reaching.\n\nTake his number away from him.",
    outro: "Ti-M\u00e8t tips his head. The board is yours to control now \u2014 he'll help you hold it.",
    featured: 'Ti-Mèt',
    title: 'Mèt Nimewo',
    theme: "He picks a number and owns it. Take it away from him.",
    unlocks: 'Ti-Mèt',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Mèt'],
        rounds: 1,
        brief: "He picks a number and owns it. Take it away from him.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Four tiles, no room for error. Empty your hand.",
        objective: { kind: 'win' },
        moves: 4,
        deal: {
          hands: [[[0, 4], [0, 1], [3, 4], [1, 2]], [[3, 6], [1, 4]], [[4, 4], [2, 4]], [[1, 6], [1, 1]]],
          board: [
            { tile: [3, 5], flipped: false },
            { tile: [5, 5], flipped: false },
            { tile: [5, 6], flipped: false },
            { tile: [2, 6], flipped: false },
            { tile: [2, 3], flipped: false }
          ],
          left_end: 3,
          right_end: 3,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Mèt', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Mèt across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Mèt'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Mèt joins your table.',
      },
    ],
  },
  {
    id: 8,
    tier: 'normal',
    intro: "Ti-Doub is the opposite of Ti-Sak, and twice as dangerous.\n\nEvery double goes down the second he can play it. No weight, no waiting, nothing left to get stuck with. By the end his hand is all easy tiles.\n\nBeat him and the small table is finished with you.",
    outro: "The small table is done. Every regular plays with you now \u2014 and word is spreading about the player who beat the whole circuit.",
    featured: 'Ti-Doub',
    title: 'Doub Rapid',
    theme: "He dumps every double the moment he can. Punish the gaps that leaves.",
    unlocks: 'Ti-Doub',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Doub'],
        rounds: 1,
        brief: "He dumps every double the moment he can. Punish the gaps that leaves.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Five tiles. The longest finish yet, and it ends on both ends.",
        objective: { kind: 'dekabess' },
        moves: 5,
        deal: {
          hands: [[[2, 2], [0, 3], [2, 3], [4, 6], [2, 6]], [[5, 6], [1, 6]], [[3, 4], [3, 6]], [[3, 3], [0, 1]]],
          board: [
            { tile: [4, 5], flipped: false },
            { tile: [2, 5], flipped: false },
            { tile: [0, 2], flipped: false },
            { tile: [0, 0], flipped: false }
          ],
          left_end: 4,
          right_end: 0,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Doub', 'Ti-Bebe', 'Ti-Bebe'],
        rounds: 1,
        brief: 'A full table, with Ti-Doub across from you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Doub'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win it and Ti-Doub joins your table.',
      },
    ],
  },

  {
    id: 9,
    tier: 'qualifier',
    intro: "They've heard about you at the big table.\n\nBefore they let you sit, the regulars want one more evening \u2014 all of them, every way they know how. Puzzles, one on one, a partner at your side, and finally the three of them playing as one against you.\n\nPass this, and the experts will see you.",
    outro: "The regulars stand up from the table. Behind them, the far door opens.\n\nThe experts have been watching.",
    featured: null,
    title: 'Kalifikasyon',
    theme: 'Everything the circuit taught you, in one sitting',
    unlocks: null,
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Doub'],
        rounds: 1,
        brief: 'The strongest of the circuit, one on one.',
      },
      {
        id: 2,
        type: 'puzzle',
        brief: 'Nobody can move much. Jam it shut while you hold the least.',
        objective: { kind: 'block' },
        moves: 1,
        deal: {
          hands: [
            [[1, 2], [1, 4], [0, 1]],
            [[5, 5], [1, 1]],
            [[2, 4], [2, 5]],
            [[1, 3], [4, 4]],
          ],
          board: [
            { tile: [0, 0], flipped: false },
            { tile: [0, 6], flipped: false },
            { tile: [5, 6], flipped: false },
            { tile: [1, 5], flipped: false },
          ],
          left_end: 0,
          right_end: 1,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Jean', 'Ti-Mèt'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner you have earned. Two of the circuit against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Djo', 'Ti-Mèt', 'Ti-Doub'],
        rounds: 1,
        brief: 'Three of them, each playing for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Djo', 'Ti-Jean', 'Ti-Doub'],
        coop: true,
        rounds: 3,
        boss: true,
        brief: 'They are working together now. Best of three — win it and the Expert Circuit opens.',
      },
    ],
  },

  {
    id: 10,
    tier: 'expert',
    intro: "Ti-J\u00f2j doesn't specialise. He just doesn't lose.\n\nNo trap, no gimmick, nothing to read. He looks at the table and plays the move that wins, and he does it every single turn.\n\nThe first of the experts, and the simplest to understand. That doesn't make him easy.",
    outro: "Ti-J\u00f2j says nothing, which from him is high praise. He sits on your side of the table now.",
    featured: 'Ti-Jòj',
    title: 'Mèt La',
    theme: "He has no trick \u2014 he simply plays better than you.",
    unlocks: 'Ti-Jòj',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Jòj'],
        rounds: 1,
        brief: "He has no trick \u2014 he simply plays better than you.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Four tiles. He wins on pure play, so take the finish he can't stop.",
        objective: { kind: 'dekabess' },
        moves: 4,
        deal: {
          hands: [[[6, 6], [0, 4], [4, 4], [4, 6]], [[0, 1], [1, 2]], [[0, 2], [2, 4]], [[0, 6], [3, 6]]],
          board: [
            { tile: [0, 5], flipped: false },
            { tile: [3, 5], flipped: false },
            { tile: [3, 3], flipped: false },
            { tile: [1, 3], flipped: false },
            { tile: [1, 1], flipped: false },
            { tile: [1, 6], flipped: false },
          ],
          left_end: 0,
          right_end: 6,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Jòj', 'Ti-Doub'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Jòj and Ti-Doub against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Jòj', 'Ti-Doub', 'Ti-Djo'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Jòj'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Jòj joins your table.',
      },
    ],
  },
  {
    id: 11,
    tier: 'expert',
    intro: "Ti-Tid never throws a double away.\n\nHe carries them like cards held back, waiting until the number is scarce and the double lands like a door closing. Play against him long enough and you'll feel it \u2014 the same number, over and over, always his.\n\nForce them out early.",
    outro: "Ti-Tid hands you a double, face down. A gift, and a warning. He plays with you now.",
    featured: 'Ti-Tid',
    title: 'Mèt Doub',
    theme: "He holds his doubles until they hurt. Force them out early.",
    unlocks: 'Ti-Tid',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Tid'],
        rounds: 1,
        brief: "He holds his doubles until they hurt. Force them out early.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Five tiles, and two of them are doubles. Order matters.",
        objective: { kind: 'win' },
        moves: 5,
        deal: {
          hands: [[[0, 1], [0, 2], [3, 3], [2, 2], [2, 6]], [[1, 1], [3, 5]], [[5, 5], [6, 6]], [[4, 5], [1, 5]]],
          board: [
            { tile: [3, 4], flipped: false },
            { tile: [4, 4], flipped: false },
            { tile: [2, 4], flipped: false },
            { tile: [2, 3], flipped: false },
            { tile: [1, 3], flipped: false },
          ],
          left_end: 3,
          right_end: 1,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Tid', 'Ti-Jòj'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Tid and Ti-Jòj against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Tid', 'Ti-Jòj', 'Ti-Doub'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Tid'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Tid joins your table.',
      },
    ],
  },
  {
    id: 12,
    tier: 'expert',
    intro: "Ti-Roro doesn't race you. He closes the room.\n\nHe'd rather jam the table holding two light tiles than go out clean. Count the pips before you think you're winning \u2014 most of the time, he already has.\n\nBeat him to the jam.",
    outro: "Ti-Roro counts his tiles one last time and pushes them aside. The Locker plays for your side now.",
    featured: 'Ti-Roro',
    title: 'Fèmen Tab',
    theme: "He wants the table jammed with him holding the least. Beat him to it.",
    unlocks: 'Ti-Roro',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Roro'],
        rounds: 1,
        brief: "He wants the table jammed with him holding the least. Beat him to it.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "His own game: jam it shut and hold the least.",
        objective: { kind: 'block' },
        moves: 1,
        deal: {
          hands: [[[3, 3], [1, 1], [1, 2]], [[6, 6], [4, 4]], [[3, 5], [1, 4]], [[4, 6], [1, 5]]],
          board: [
            { tile: [1, 6], flipped: false },
            { tile: [5, 6], flipped: false },
            { tile: [5, 5], flipped: false },
            { tile: [4, 5], flipped: false },
            { tile: [0, 4], flipped: false },
          ],
          left_end: 1,
          right_end: 0,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Roro', 'Ti-Jòj'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Roro and Ti-Jòj against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Roro', 'Ti-Jòj', 'Ti-Tid'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Roro'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Roro joins your table.',
      },
    ],
  },
  {
    id: 13,
    tier: 'expert',
    intro: "Ti-Chas\u00e8 keeps both ends where he wants them.\n\nThe numbers he's deep in stay open; the ones you need disappear. You'll have a full hand and nowhere to put any of it.\n\nTake his numbers before he takes yours.",
    outro: "Ti-Chas\u00e8 lets go of the board. You control the ends now \u2014 with him helping.",
    featured: 'Ti-Chasè',
    title: 'Kontwòl',
    theme: "He keeps the ends on numbers he owns. Take those numbers away.",
    unlocks: 'Ti-Chasè',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Chasè'],
        rounds: 1,
        brief: "He keeps the ends on numbers he owns. Take those numbers away.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Five tiles, four of them zeros. Control the ends, then close.",
        objective: { kind: 'dekabess' },
        moves: 5,
        deal: {
          hands: [[[0, 3], [0, 2], [0, 5], [0, 6], [2, 6]], [[4, 6], [3, 5]], [[6, 6], [3, 6]], [[0, 4], [2, 3]]],
          board: [
            { tile: [3, 4], flipped: false },
            { tile: [4, 4], flipped: false },
            { tile: [1, 4], flipped: false },
            { tile: [1, 5], flipped: false },
            { tile: [5, 5], flipped: false },
          ],
          left_end: 3,
          right_end: 5,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Chasè', 'Ti-Tid'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Chasè and Ti-Tid against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Chasè', 'Ti-Tid', 'Ti-Roro'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Chasè'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Chasè joins your table.',
      },
    ],
  },
  {
    id: 14,
    tier: 'expert',
    intro: "Ti-Fr\u00e8 doesn't play for himself.\n\nEverything he does is for the man across from him \u2014 opening his numbers, eating the bad turns, going out second so his partner goes out first. Against a pair like that you're not playing one opponent.\n\nBreak them up.",
    outro: "Ti-Fr\u00e8 moves his chair to your side without being asked. That's who he is.",
    featured: 'Ti-Frè',
    title: 'Asosye',
    theme: "He plays for his partner, not himself. Break up the pair.",
    unlocks: 'Ti-Frè',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Frè'],
        rounds: 1,
        brief: "He plays for his partner, not himself. Break up the pair.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Empty your hand before the table closes on you.",
        objective: { kind: 'win' },
        moves: 5,
        deal: {
          hands: [[[0, 3], [4, 4], [3, 3], [0, 4], [0, 5]], [[1, 4], [1, 3]], [[2, 3], [4, 6]], [[3, 6], [4, 5]]],
          board: [
            { tile: [3, 5], flipped: false },
            { tile: [5, 6], flipped: false },
            { tile: [6, 6], flipped: false },
            { tile: [2, 6], flipped: false },
            { tile: [2, 2], flipped: false },
            { tile: [2, 5], flipped: false },
          ],
          left_end: 3,
          right_end: 5,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Frè', 'Ti-Roro'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Frè and Ti-Roro against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Frè', 'Ti-Roro', 'Ti-Chasè'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Frè'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Frè joins your table.',
      },
    ],
  },
  {
    id: 15,
    tier: 'expert',
    intro: "Ti-Chaj counts what's gone.\n\nHe plays the last of a number and it never comes back \u2014 and anyone still holding it is holding it forever. You won't notice until you're sitting on three tiles that can't ever be played.\n\nWatch what leaves the table.",
    outro: "Ti-Chaj taps the dead numbers on the table, one by one, showing you what you missed. Now he counts for you.",
    featured: 'Ti-Chaj',
    title: 'Konte',
    theme: "He kills numbers off the board. Watch which ones are already gone.",
    unlocks: 'Ti-Chaj',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Chaj'],
        rounds: 1,
        brief: "He kills numbers off the board. Watch which ones are already gone.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "He counts what's gone. Kill the board while you're light.",
        objective: { kind: 'block' },
        moves: 1,
        deal: {
          hands: [[[0, 0], [2, 4], [1, 5], [1, 1]], [[3, 6], [4, 6]], [[3, 3], [0, 6]], [[4, 4], [5, 6]]],
          board: [
            { tile: [2, 2], flipped: false },
            { tile: [1, 2], flipped: false },
            { tile: [1, 3], flipped: false },
            { tile: [3, 4], flipped: false },
          ],
          left_end: 2,
          right_end: 4,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Chaj', 'Ti-Chasè'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Chaj and Ti-Chasè against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Chaj', 'Ti-Chasè', 'Ti-Frè'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Chaj'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Chaj joins your table.',
      },
    ],
  },
  {
    id: 16,
    tier: 'expert',
    intro: "Ti-Py\u00e8j waits for the table to seize.\n\nHe wants the moment nobody can move \u2014 and he wants you in it, holding everything. He'll open a number just to watch you walk into it three turns later.\n\nSee the trap before you're in it.",
    outro: "Ti-Py\u00e8j smiles like he set this up too. Maybe he did. Either way, he's yours.",
    featured: 'Ti-Pyèj',
    title: 'Pyèj',
    theme: "He hunts the moment the table seizes. Don't walk into it.",
    unlocks: 'Ti-Pyèj',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Pyèj'],
        rounds: 1,
        brief: "He hunts the moment the table seizes. Don't walk into it.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "He sets traps several moves out. Set one of your own.",
        objective: { kind: 'dekabess' },
        moves: 5,
        deal: {
          hands: [[[0, 0], [3, 3], [0, 5], [3, 4], [4, 5]], [[0, 3], [4, 6]], [[2, 5], [3, 6]], [[0, 6], [2, 4]]],
          board: [
            { tile: [0, 2], flipped: false },
            { tile: [1, 2], flipped: false },
            { tile: [1, 6], flipped: false },
            { tile: [2, 6], flipped: false },
            { tile: [2, 2], flipped: false },
            { tile: [2, 3], flipped: false },
          ],
          left_end: 0,
          right_end: 3,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Pyèj', 'Ti-Frè'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Pyèj and Ti-Frè against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Pyèj', 'Ti-Frè', 'Ti-Chaj'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Pyèj'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Pyèj joins your table.',
      },
    ],
  },
  {
    id: 17,
    tier: 'expert',
    intro: "Ti-Wa reads the table, not the tiles.\n\nHe knows who's dangerous and goes straight at them, and tonight that's you. Everything the experts taught you, he already knows you learned.\n\nOne more, and the circuit is yours.",
    outro: "Ti-Wa stands and offers his seat \u2014 the good one, facing the door.\n\nOnly the championship is left.",
    featured: 'Ti-Wa',
    title: 'Li Tab La',
    theme: "He reads who is dangerous and goes after them. Today that's you.",
    unlocks: 'Ti-Wa',
    challenges: [
      {
        id: 1,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Wa'],
        rounds: 1,
        brief: "He reads who is dangerous and goes after them. Today that's you.",
      },
      {
        id: 2,
        type: 'puzzle',
        brief: "Six tiles, one path. The longest finish in the circuit.",
        objective: { kind: 'win' },
        moves: 6,
        deal: {
          hands: [[[3, 3], [3, 5], [1, 4], [3, 4], [3, 6], [2, 3]], [[0, 5], [1, 1]], [[5, 6], [0, 6]], [[4, 4], [0, 1]]],
          board: [
            { tile: [1, 6], flipped: false },
            { tile: [6, 6], flipped: false },
            { tile: [4, 6], flipped: false },
            { tile: [0, 4], flipped: false },
            { tile: [0, 2], flipped: false },
          ],
          left_end: 1,
          right_end: 2,
          turn: 0,
        },
      },
      {
        id: 3,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Wa', 'Ti-Chaj'],
        partner: 'pick',
        rounds: 1,
        brief: 'Pick a partner. Ti-Wa and Ti-Chaj against the two of you.',
      },
      {
        id: 4,
        type: 'match',
        seats: 4,
        opponents: ['Ti-Wa', 'Ti-Chaj', 'Ti-Pyèj'],
        rounds: 1,
        brief: 'Three of them, each for themselves.',
      },
      {
        id: 5,
        type: 'match',
        seats: 2,
        pile: true,
        opponents: ['Ti-Wa'],
        rounds: 3,
        boss: true,
        brief: 'Best of three. Win and Ti-Wa joins your table.',
      },
    ],
  },

  {
    id: 18,
    tier: 'final',
    intro: "Everyone is here.\n\nThe regulars along the wall, the experts at the table, and the door closed behind you. Five rounds, every kind of game they know, and then the last one \u2014 just you and Ti-Wa, however long it takes.\n\nThis is what the small table was for.",
    outro: "They push the table back and stand.\n\nYou came in knowing how to place a tile. You're leaving as the one they'll be telling stories about.\n\nDekabess.",
    featured: 'Ti-Wa',
    title: 'Chanpyona',
    theme: 'Five rounds, then the Master',
    unlocks: null,
    challenges: [
      { id: 1, type: 'puzzle',
        brief: 'Six tiles and one way home. Open the championship with a Dekabess.',
        objective: { kind: 'dekabess' }, moves: 6,
        deal: {
          hands: [[[5,6],[2,5],[1,1],[1,6],[5,5],[1,2]],[[1,4],[0,0]],[[3,3],[0,3]],[[1,3],[3,5]]],
          board: [
            { tile: [6,6], flipped: false },
            { tile: [3,6], flipped: false },
            { tile: [2,3], flipped: false },
            { tile: [2,4], flipped: false },
            { tile: [4,6], flipped: false }
          ],
          left_end: 6, right_end: 6, turn: 0,
        } },
      { id: 2, type: 'match', seats: 2, pile: true, opponents: ['Ti-Roro'], rounds: 3,
        brief: 'One on one with the Locker.' },
      { id: 3, type: 'match', seats: 4, opponents: ['Ti-Jòj', 'Ti-Pyèj'], partner: 'pick', rounds: 3,
        brief: 'Choose anyone you have earned. Two experts across the table.' },
      { id: 4, type: 'match', seats: 4, opponents: ['Ti-Chaj', 'Ti-Chasè', 'Ti-Tid'], rounds: 3,
        brief: 'Three experts, each playing for themselves.' },
      { id: 5, type: 'match', seats: 4, opponents: ['Ti-Jòj', 'Ti-Roro', 'Ti-Pyèj'], coop: true, rounds: 3,
        brief: 'Team attack. The three of them are playing as one.' },
      { id: 6, type: 'match', seats: 2, pile: true, opponents: ['Ti-Wa'], rounds: 3, boss: true,
        brief: 'The championship. Best of three against the Reader.' },
    ],
  },
]

// A bot is available as a partner or free-play opponent once its chapter is
// done — except the featured bot of the chapter being played.
export function availableBots(progress, chapter) {
  const unlocked = progress?.unlocked_bots || []
  return unlocked.filter(b => b !== chapter?.featured)
}
